version: "1.0"

services:
    url-shortener:
        build: ./app
        depends_on:
            - db
            - redis
        ports:
            - 5000:5000
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: "db"
            MYSQL_USER: "cooluser"
            MYSQL_PASSWORD: "coolpassword"
            MYSQL_ROOT_PASSWORD: "password"
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - my-db:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    redis:
        image: redis
        restart: always
        ports:
            - 6378:6378
        command: redis-server --save 20 1 --loglevel warning --bind redis --port 6378
        volumes:
            - cache:/data
volumes:
    my-db:
    cache:
        driver: local
